### ISSUE TITLE
`gulp check` errors. Windows dev support?

### ISSUE THREAD

**Issue by aaroncalderon** [electrode-io/electrode-io.github.io#314]
# Question

Is the expected dev environment expected to be Linux?

# Background

I was reviewing the documentation and on the [Test Component](http://www.electrode.io/docs/test_components.html) step I got some errors:

```
[16:15:21] Using gulpfile C:\dev\p\electrode\electrode-component\gulpfile.js
[16:15:21] Starting 'check'...
[16:15:21] Starting 'check-dep'...
Check dependencies passed
[16:15:24] Finished 'check-dep' after 2.64 s
[16:15:24] Starting 'lint'...
[16:15:24] Starting 'lint-stylus'...
-d was unexpected at this time.
[16:15:24] 'lint-stylus' errored after 22 ms
[16:15:24] Error: command exit code 1
    at error (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
    at shell.exec (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29)
    at C:\dev\p\electrode\electrode-component\node_modules\shelljs\src\exec.js:180:7
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[16:15:24] 'check' errored after 2.68 s
[16:15:24] Error in plugin 'run-sequence(lint-stylus)'
Message:
    command exit code 1
Details:
    stdout:
    stderr: -d was unexpected at this time.

Stack:
Error: command exit code 1
    at error (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
    at shell.exec (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29)
    at C:\dev\p\electrode\electrode-component\node_modules\shelljs\src\exec.js:180:7
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[16:15:24] 'lint' errored after 31 ms
[16:15:24] Error in plugin 'run-sequence(check)'
Message:
    command exit code 1
Details:
    stdout:
    stderr: -d was unexpected at this time.

Stack:
Error: command exit code 1
    at error (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
    at shell.exec (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29)
    at C:\dev\p\electrode\electrode-component\node_modules\shelljs\src\exec.js:180:7
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[16:15:24] 'lint' errored after 33 ms
[16:15:24] Error in plugin 'run-sequence(lint-stylus)'
Message:
    command exit code 1
Details:
    stdout:
    stderr: -d was unexpected at this time.

Stack:
Error: command exit code 1
    at error (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:6:15)
    at shell.exec (C:\dev\p\electrode\electrode-component\node_modules\electrode-gulp-helper\lib\exec.js:19:29)
    at C:\dev\p\electrode\electrode-component\node_modules\shelljs\src\exec.js:180:7
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

# Findings

As I looked arouond the code base I spoted that on [archetype-gulpfile.js#L115](https://github.com/electrode-io/electrode-archetype-react-component/blob/master/archetype-gulpfile.js#L115) the command reads `if [ -d src/styles ]; then stylint src/styles -c ${__dirname}/config/stylint/.stylintrc; else echo 'Skipping Stylint as no src/styles directory'; fi` and the error states:

```
Details:
    stdout:
    stderr: -d was unexpected at this time.
```

so it makes me think if this are commands that expect a Linux dev environment since it is using `if..fi` shell commands.

Can we clarify if a Linux dev environment is requiered or recommended on the documentation?

Thanks

**Comment by ananavati** [comment]
closing this and merging into https://github.com/electrode-io/electrode-io.github.io/issues/314
