### ISSUE TITLE
get started steps do not work

### ISSUE THREAD

**Issue by ograycode** [electrode-io/electrode-io.github.io#381]
**Issue**

Following the [Get Started](http://www.electrode.io/docs/get_started.html) does not work. When you do `guip dev` it complains that `AssertionError: dev archetype is missing - development & build tasks not possible`.

**Repo Steps**

Follow the Get Started steps.

**Stack Trace**

```
$ gulp dev
 
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: dev archetype is missing - development & build tasks not possible
    at Object.<anonymous> (/usr/lib/node_modules/electrode-archetype-react-app/arch-gulpfile.js:7:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mechagojira/stats/gulpfile.js:1:63)
    at Module._compile (module.js:570:32)

```

**Other**

It looks like the repo for `electrode-archetype-react-app` no longer exists (at least I could not find it)

**Comment by ograycode** [comment]
Nevermind, rebuilt the server and made sure `apt-get update` ran before installing node/git/build-essentials and now it works.
